name: CF Pages Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.2.2
      # 官方pnpm安装action，自动配置环境变量
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Build static for CF Pages
        run: pnpm build
